In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([[500], [800], [1000], [1200], [1500]])  
y = np.array([150, 200, 250, 280, 350])              

model = LinearRegression()
model.fit(X, y)

pred = model.predict([[1100]])

print("Intercept:", model.intercept_)
print("Slope:", model.coef_)
print("Predicted price:", pred[0])

Intercept: 45.99999999999994
Slope: [0.2]
Predicted price: 266.0


In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

X = np.array([
    [1000, 2],
    [1500, 3],
    [1800, 3],
    [2400, 4],
    [3000, 4]
])

y = np.array([200, 300, 350, 400, 500])

model = LinearRegression()
model.fit(X, y)

y_pred = model.predict(X)

print("Predictions:", y_pred)
print("R2 Score:", r2_score(y, y_pred))

Predictions: [215.83113456 288.39050132 329.94722955 416.35883905 499.47229551]
R2 Score: 0.978891820580475


In [3]:
import numpy as np
from sklearn.linear_model import LogisticRegression

marks = np.array([[35], [40], [45], [50], [55], [60]])
result = np.array([0,0,0,1,1,1])  # 0=Fail, 1=Pass

model = LogisticRegression()
model.fit(marks, result)

pred = model.predict([[48]])

print("Prediction (0=Fail,1=Pass):", pred[0])

Prediction (0=Fail,1=Pass): 1


In [4]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()

X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, test_size=0.3)

model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.9555555555555556


In [5]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

data = load_iris()

X_train, X_test, y_train, y_test = train_test_split(
    data.data, data.target, test_size=0.3)

model = DecisionTreeClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix:
[[14  0  0]
 [ 0 13  0]
 [ 0  2 16]]
